# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f8ea744ce5a1050202472836563c267be804cc815d6fe8f710f1edbbba82fc961da94fbf28eca7d550ac1a9cb1535f65fb5d1978feef28000364d5e45f4edf7

test:
  secret_key_base: 8d5fd8f13a7cbc29472064580c462791722befd70e74a2da3e316896bba1b1e9fccb8fd6bab42302d7281ffa6e80f5e0875666610d35a021f1bee19e25e24c2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
