
User.create!([
  {last_name: "Chou", first_name: "James", username: "jameschou", password_digest: "$2a$10$.M5yjiO5rCwdO222pKMHoum/GaWk2bMxUGRoHEX9KniNxP.B4WL..", email: "james@chou.com"},
  {last_name: "Carleton Schowalter", first_name: "Tyshawn Hauck", username: "Faker::Pokemon", password_digest: "$2a$10$r4n9KyRlcdzKCJ5kM.OFXua0Q7J679wgpmvgvqnzmWrVc7.nsDiTG", email: "Faker::Pokemon@mail.com"},
  {last_name: "Antoinette Feeney", first_name: "Gladys Grimes", username: "Pidgey", password_digest: "$2a$10$J35k0Uw/n4POCz8noT/C9OG/ZQozh6Sr4Eyy5.3n48LiraTJf5AJS", email: "delaney@dietrichreichel.info"},
  {last_name: "Ms. Brittany Upton", first_name: "Maudie Schoen", username: "Vileplume", password_digest: "$2a$10$pkQw.BsnPG.v8Dt4l5t.zO6i3rcWw2VSG.QzymaKZg6uoI7NMiAYy", email: "neoma.hammes@mante.io"},
  {last_name: "Aurelio Jakubowski", first_name: "Montana Volkman", username: "Raticate", password_digest: "$2a$10$iTgyz.mzqfdQn.jUujc8hOa6Zy7n27dSXkH2IjEqpyZMact5WphEK", email: "darien.lemke@mcculloughmuller.biz"},
  {last_name: "Ara Kemmer", first_name: "Paul Crona", username: "Magnemite", password_digest: "$2a$10$mEYDF/dutnIvizS1.PeUnOkju7FY5W75Ji7FiAJAKqR8K6w75xhfe", email: "magali@kulaswelch.co"},
  {last_name: "Kali McClure", first_name: "Ms. Rudolph Cummings", username: "Bulbasaur", password_digest: "$2a$10$oM4SxuMXj1CNYWErRMBb4OTyTFm/z98bytMKtrUMLbt2n90PKNBwW", email: "malachi.gislason@ebertgibson.biz"},
  {last_name: "Laury Becker", first_name: "Coy Wuckert", username: "Nidoran", password_digest: "$2a$10$0KoYVtrddz1s2ALGyTlYvOpbHE36bsvEHc..RXcE4tfD7uZrWDohq", email: "alec_watsica@lindgrenbradtke.name"},
  {last_name: "Alysha Harvey", first_name: "Jayda Hahn", username: "Moltres", password_digest: "$2a$10$zgY/et9AxlQNw/706N6EBuGquBEeCFFhK6QfJyGKHidiu/Db05A36", email: "percy@crooks.org"},
  {last_name: "Torrey Runolfsson", first_name: "Halle Mitchell DVM", username: "Charmeleon", password_digest: "$2a$10$hJSI29qvAJec1MbIT2xpDOVHm23fwLZ0UB0MOH/qp9W8X95sxJOTu", email: "emelia@ratke.io"},
  {last_name: "Emmett Kling Sr.", first_name: "Mr. Wilson Leannon", username: "Growlithe", password_digest: "$2a$10$JBGBfJmMv2Ra9PFewSeevOiAlZDqtD1onMKHUEk3IBBS5hoBwQh3a", email: "coleman@hansen.org"},
  {last_name: "Ms. Nathan Windler", first_name: "Macey Keeling", username: "Zubat", password_digest: "$2a$10$iGAfJ6aR.I7UpvSH/TLK/uMxegZWBN6SAHtiN.ELnmRct/34Quqou", email: "tracy@hauck.name"},
  {last_name: "Claire Metz", first_name: "Harvey Daniel DDS", username: "Kakuna", password_digest: "$2a$10$YX4zS6.6vZYrwVTBqByF9uXsUpiWREXpgfLmN7DjN2K4eeF1pzldO", email: "mozell@roob.co"},
  {last_name: "Mr. Kathlyn Collins", first_name: "Lillian Gaylord V", username: "Omastar", password_digest: "$2a$10$F25LBH80iJRcywiZFbG1meqcNF2D0BXOallzwnsYnVGd.svpWVjb2", email: "aylin@okeefe.co"},
  {last_name: "Crystel Kulas", first_name: "Rafaela Little", username: "Seadra", password_digest: "$2a$10$WFw3LEh3zIi8cXXjwuVABu8fGqWo3fdNimGht0eHv69bVoV41h4cy", email: "marilie.hudson@green.net"},
  {last_name: "Joy Koch MD", first_name: "Bruce Bartell", username: "Sandslash", password_digest: "$2a$10$WnRwf/tl5sO2XrCi8wPqFeFDMOHr8T6wM8H.gZP93/SZTkzFr0LV.", email: "patrick_cain@muller.name"},
  {last_name: "Kathlyn Rippin", first_name: "Reyna Witting", username: "Kingler", password_digest: "$2a$10$sLBDPy1A2HWGvBNd4P.SoOZpPPBkbPwuulsoC.FLHq8nppml8VQjm", email: "alden.dibbert@kulas.info"},
  {last_name: "Webster Price DDS", first_name: "Theresa Abshire", username: "Spearow", password_digest: "$2a$10$8fJ2xf83xS9xc6Io27Y9ZunmtGe29Lzf2GtbrP0MB13c8.tNhnXam", email: "ola_durgan@parisian.io"},
  {last_name: "Alena Von", first_name: "Lucius Schaden", username: "Oddish", password_digest: "$2a$10$lQbULK7QnFwcroDff3yO1ezyYSc28k6clrcCSNeU1ZzNsx2r5WgFm", email: "leora@altenwerth.biz"},
  {last_name: "Winifred Greenfelder", first_name: "Maximo Cummings Sr.", username: "Seel", password_digest: "$2a$10$UiRUQO217QT2svTr/6m2zOvWc9nvIidLzFKalN7x9W2XkjTXpYiR.", email: "pattie@kris.net"},
  {last_name: "Shannon Stamm", first_name: "Neha O'Keefe", username: "Beedrill", password_digest: "$2a$10$AFBy5YP1AxS72wrC.nZCHOysgEiB8Jg4G7KcmkGd.kE9MQn2Di8Ni", email: "autumn@heidenreich.biz"},
  {last_name: "Man", first_name: "pac", username: "pacman", password_digest: "$2a$10$LhgZFW4TCHehjqL26yitAe.GJRvTAu/WufWW.q0aQZHOp.ybb.Wbq", email: "pac@man.com"},
  {last_name: "Jenkins", first_name: "Leeroy", username: "leejenks", password_digest: "$2a$10$aPlOANnY97c/zrS3XNQDfuICv3rkpGlcSF5OlqP12Y9lMIZjJMXXq", email: "leeroy@jenkins.org"},
  {last_name: "Mama", first_name: "Joe", username: "jmama", password_digest: "$2a$10$IkE1k3vL8uOM9z3KVR/LAODL/lhQT.d5FBKnlW/1JNXytIc7y6fdC", email: "joe@mama.com"},
  {last_name: "Prada", first_name: "Hailey", username: "haipra", password_digest: "$2a$10$jw8KoJq5mH5zyN0/eRtqWOajFSY0QQVKtsoTEj6CpyElZ6tqLP5UG", email: "hp@gmail.com"},
  {last_name: "Prada", first_name: "Olivia", username: "olipra", password_digest: "$2a$10$0LrwsOYdt7KGG8T8ka4c7u6O9PTYESz5TvYIHInpv2YMiFBT35L/y", email: "op@gmail.com"},
  {last_name: "Wang", first_name: "Mikaela", username: "Mikwan", password_digest: "$2a$10$FiDthp41jGIjd/DCkmXJG.hAVg4q5O0NmV/5w36j/LIEy4xK5N9Km", email: "mwang@gmail.com"}
])
Group.create!([
  {name: "Jack Spy Me", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: false},
  {name: "Edna O'Brien", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: false},
  {name: "Blood's a Rover", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: true},
  {name: "actualize", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: false},
  {name: "Hack Slashers", bio: "  We like to code and slash", private?: false},
  {name: "Tiger! Tiger!", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: false},
  {name: "A Summer Bird-Cage", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: true},
  {name: "The Millstone", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: true},
  {name: "WE FIT", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: true},
  {name: "Postern of Fate", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: true},
  {name: "The Knights of the Round Table", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: true},
  {name: "Ironman Fitness Club", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: true},
  {name: "The Mermaids Singing", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: false},
  {name: "A Scanner Darkly", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: false},
  {name: "Dis Group", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: false},
  {name: "Catfishing", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: false},
  {name: "Foodies Unite", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: false},
  {name: "The Stars' Tennis Balls", bio: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", private?: true},
  {name: "Vivian's Army", bio: "Vivian's fan group gone rogue  ", private?: true}
])
GroupCategory.create!([
Appointment.create!([
  {title: "Jogging", location_id: 2, start_time: "21:00", end_time: "18:00", date: "2017-06-30"},
  {title: "March", location_id: 1, start_time: "20:00", end_time: "10:00", date: "2017-03-13"},
  {title: "Play Video Games", location_id: 21, start_time: "12:00", end_time: "19:00", date: "2017-09-18"},
  {title: "Take out the Trash", location_id: 22, start_time: "7:00", end_time: "13:00", date: "2017-05-13"},
  {title: "Eat Almonds", location_id: 14, start_time: "16:00", end_time: "22:00", date: "2017-03-14"},
  {title: "Chuck Norris doesn't have disk latency because the hard drive knows to hurry the hell up.", location_id: 22, start_time: "time", end_time: "time", date: "2018-01-06"},
  {title: "Chuck Norris can write infinite recursion functions... and have them return.", location_id: 6, start_time: "time", end_time: "time", date: "2017-06-10"},
  {title: "Chuck Norris doesn't need an OS.", location_id: 6, start_time: "time", end_time: "time", date: "2018-02-14"},
  {title: "Chuck Norris compresses his files by doing a flying round house kick to the hard drive.", location_id: 3, start_time: "time", end_time: "time", date: "2017-12-15"},
  {title: "Chuck Norris compresses his files by doing a flying round house kick to the hard drive.", location_id: 11, start_time: "time", end_time: "time", date: "2017-09-15"},
  {title: "Chuck Norris' preferred IDE is hexedit.", location_id: 21, start_time: "time", end_time: "time", date: "2017-03-26"},
  {title: "Chuck Norris burst the dot com bubble.", location_id: 4, start_time: "time", end_time: "time", date: "2017-06-27"},
  {title: "Chuck Norris doesn't need an OS.", location_id: 15, start_time: "time", end_time: "time", date: "2017-03-14"},
  {title: "Hot Sauce Rally", location_id: 4, start_time: "12:21", end_time: "02:22", date: "21233-12-12"},
  {title: "Javascript101", location_id: 1, start_time: "1:00PM", end_time: "3:00PM", date: "2017-03-08"},
  {title: "Lunchbreak1", location_id: 2, start_time: "11:00AM", end_time: "4:00PM", date: "2017-03-08"},
  {title: "Harry Potter Puppet Show", location_id: 21, start_time: "14:12", end_time: "16:02", date: "2017-03-08"},
  {title: "Pajama Party", location_id: 15, start_time: "14:02", end_time: "16:00", date: "2017-03-19"},
  {title: "PieCaken Party", location_id: 5, start_time: "09:57", end_time: "22:57", date: "2015-12-28"},
  {title: "Learn Geocoder", location_id: 23, start_time: "00:57", end_time: "22:58", date: "2017-12-31"},
  {title: "St. Patrick's Day", location_id: 24, start_time: "00:00", end_time: "12:00", date: "2017-03-17"},
  {title: "Cheezit factory tour", location_id: 25, start_time: "00:59", end_time: "22:58", date: "2017-03-20"},
  {title: "Chores", location_id: 20, start_time: "22:00", end_time: "21:00", date: "2018-03-23"},
  {title: "Watch Tv", location_id: 21, start_time: "19:00", end_time: "13:00", date: "2018-03-23"},
  {title: "Tour ", location_id: 19, start_time: "11:00", end_time: "3:00", date: "2018-03-23"},
  {title: "Ridicule ", location_id: 16, start_time: "5:00", end_time: "18:00", date: "2018-03-23"},
  {title: "Hangout", location_id: 18, start_time: "19:00", end_time: "23:00", date: "2018-03-23"},
  {title: "Chuck Norris finished World of Warcraft.", location_id: 17, start_time: "time", end_time: "time", date: "2018-03-23"},
  {title: "Chuck Norris can read all encrypted data, because nothing can hide from Chuck Norris.", location_id: 18, start_time: "time", end_time: "time", date: "2018-03-23"},
  {title: "Hot Sauce Rally", location_id: 16, start_time: "00:12", end_time: "02:32", date: "2018-03-23"}
])
Category.create!([
  {name: "education"},
  {name: "food"},
  {name: "technology"},
  {name: "crafts"},
  {name: "fashion"},
  {name: "excerise"},
  {name: "health"},
  {name: "alcohol"},
  {name: "carpentry"},
  {name: "astrology"}
])
  {group_id: 1, category_id: 4},
  {group_id: 2, category_id: 2},
  {group_id: 2, category_id: 1},
  {group_id: 5, category_id: 5},
  {group_id: 2, category_id: 2},
  {group_id: 8, category_id: 5},
  {group_id: 7, category_id: 4},
  {group_id: 10, category_id: 3},
  {group_id: 5, category_id: 8},
  {group_id: 2, category_id: 2},
  {group_id: 8, category_id: 5},
  {group_id: 3, category_id: 4},
  {group_id: 8, category_id: 5},
  {group_id: 6, category_id: 10},
  {group_id: 4, category_id: 5},
  {group_id: 6, category_id: 3},
  {group_id: 3, category_id: 1},
  {group_id: 10, category_id: 7},
  {group_id: 13, category_id: 1},
  {group_id: 13, category_id: 2},
  {group_id: 13, category_id: 5},
  {group_id: 13, category_id: 9},
  {group_id: 13, category_id: 10},
  {group_id: 14, category_id: 3},
  {group_id: 14, category_id: 4},
  {group_id: 14, category_id: 6},
  {group_id: 14, category_id: 8},
  {group_id: 15, category_id: 1},
  {group_id: 15, category_id: 6},
  {group_id: 15, category_id: 7},
  {group_id: 16, category_id: 2},
  {group_id: 16, category_id: 3},
  {group_id: 17, category_id: 6},
  {group_id: 17, category_id: 7},
  {group_id: 12, category_id: 2},
  {group_id: 12, category_id: 8},
  {group_id: 18, category_id: 1},
  {group_id: 18, category_id: 3},
  {group_id: 18, category_id: 5},
  {group_id: 18, category_id: 6},
  {group_id: 19, category_id: 1},
  {group_id: 19, category_id: 2},
  {group_id: 19, category_id: 4},
  {group_id: 19, category_id: 5}
])
Location.create!([
  {address: "123 fake street", city: "Idaho", state: "Idaho", zip_code: 11111, phone: "123-123-1232", latitude: 40.704751, longitude: -74.006027},
  {address: "123 real street", city: "DetroitRocko", state: "Michigan", zip_code: 212311, phone: "123-123-1232", latitude: 40.704751, longitude: -74.006027},
  {address: "395 Kennedy Estate", city: "South Allan", state: "Minnesota", zip_code: 71459, phone: "(312) 170-9197", latitude: 40.704751, longitude: -74.006027},
  {address: "9844 Lawrence Island", city: "Conroyfort", state: "Wisconsin", zip_code: 36164, phone: "(210) 595-8391", latitude: 40.704751, longitude: -74.006027},
  {address: "5549 Weimann Rest", city: "O'Connerport", state: "Florida", zip_code: 42542, phone: "(362) 690-6974", latitude: 40.704751, longitude: -74.006027},
  {address: "374 Royce Crossroad", city: "North Westley", state: "Louisiana", zip_code: 25117, phone: "(394) 497-0471", latitude: 40.704751, longitude: -74.006027},
  {address: "89964 Hank Turnpike", city: "South Carleeberg", state: "South Dakota", zip_code: 46192, phone: "1-543-073-5073", latitude: 40.704751, longitude: -74.006027},
  {address: "8175 Bartoletti Coves", city: "Stokeshaven", state: "New York", zip_code: 74794, phone: "287-079-5736", latitude: 40.704751, longitude: -74.006027},
  {address: "62195 Geovany Turnpike", city: "East Jasminton", state: "Alaska", zip_code: 19871, phone: "(220) 779-9381", latitude: 40.704751, longitude: -74.006027},
  {address: "9151 Jacobson Point", city: "Wolfchester", state: "Iowa", zip_code: 90051, phone: "(827) 225-9981", latitude: 40.704751, longitude: -74.006027},
  {address: "869 Spinka Roads", city: "Brooksstad", state: "New York", zip_code: 25694, phone: "682-500-6522", latitude: 40.704751, longitude: -74.006027},
  {address: "98618 Kuhn Grove", city: "Port Rodrigo", state: "Alaska", zip_code: 29936, phone: "520-985-4968", latitude: 40.704751, longitude: -74.006027},
  {address: "466 Funk Land", city: "New Jordon", state: "Pennsylvania", zip_code: 66851, phone: "594-282-1254", latitude: 40.704751, longitude: -74.006027},
  {address: "680 Ona Street", city: "Trompside", state: "Indiana", zip_code: 24182, phone: "1-322-933-9740", latitude: 40.704751, longitude: -74.006027},
  {address: "2670 Fadel Drives", city: "South Brandynburgh", state: "Hawaii", zip_code: 19398, phone: "(726) 115-1633", latitude: 40.704751, longitude: -74.006027},
  {address: "815 Hilton Throughway", city: "New Rafaelport", state: "Kentucky", zip_code: 35675, phone: "1-562-814-6747", latitude: 40.704751, longitude: -74.006027},
  {address: "98607 Funk Glen", city: "New Brooklyn", state: "Alaska", zip_code: 96307, phone: "941.849.2440", latitude: 40.704751, longitude: -74.006027},
  {address: "15592 Cartwright Mill", city: "New Alaynaside", state: "Connecticut", zip_code: 29067, phone: "1-204-417-9055", latitude: 40.704751, longitude: -74.006027},
  {address: "120 Wall Street", city: "New York", state: "NY", zip_code: 10005, phone: nil, latitude: 40.704751, longitude: -74.006027},
  {address: "590 Bessie Springs", city: "South Prudence", state: "New Hampshire", zip_code: 88701, phone: "718-763-7496", latitude: 41.704751, longitude: -74.106027},
  {address: "2192 Kub Parks", city: "Kleinhaven", state: "Colorado", zip_code: 77515, phone: "(899) 238-4260", latitude: 41.704751, longitude: -74.006027},
  {address: "81026 Alexandra Haven", city: "Monserratburgh", state: "Vermont", zip_code: 52497, phone: "630.097.6504", latitude: 33.704751, longitude: -74.006027},
  {address: "795 Pouros Neck", city: "Eddtown", state: "Alabama", zip_code: 95275, phone: "1-903-875-1467", latitude: 39.704751, longitude: -74.006027},
  {address: "200 42nd Street", city: "New York", state: "NEW YORK", zip_code: 10055, phone: nil, latitude: 40.7503996, longitude: -73.9746165},
  {address: "120 14th street", city: "New York", state: "NY", zip_code: 10013, phone: nil, latitude: 40.7376125, longitude: -73.9982873}
])
Message.create!([
  {body: "heyllo", user_id: 22, group_id: 1},
  {body: "HIIIII", user_id: 22, group_id: 1},
  {body: "HIIIII", user_id: 22, group_id: 1},
  {body: "HIIIII", user_id: 22, group_id: 1},
  {body: "JOE MAMA", user_id: 22, group_id: 1},
  {body: "JOE MAMA", user_id: 22, group_id: 1},
  {body: "Hello", user_id: 22, group_id: 1},
  {body: "CHEESE", user_id: 25, group_id: 1},
  {body: "asdf", user_id: 22, group_id: 1},
  {body: "ffsd", user_id: 22, group_id: 1},
  {body: "LONGGGGG", user_id: 22, group_id: 1},
  {body: "eyyyy", user_id: 22, group_id: 1},
  {body: "eyyyy", user_id: 22, group_id: 1},
  {body: "dadf", user_id: 22, group_id: 1},
  {body: "dadf", user_id: 22, group_id: 1},
  {body: "asdfasdf", user_id: 22, group_id: 1},
  {body: "dasfasfd", user_id: 22, group_id: 1},
  {body: "I need some help", user_id: 22, group_id: 2}
])

UserAppointment.create!([
  {user_id: 15, appointment_id: 2},
  {user_id: 5, appointment_id: 2},
  {user_id: 6, appointment_id: 2},
  {user_id: 17, appointment_id: 2},
  {user_id: 17, appointment_id: 2},
  {user_id: 4, appointment_id: 2},
  {user_id: 8, appointment_id: 1},
  {user_id: 13, appointment_id: 1},
  {user_id: 4, appointment_id: 2},
  {user_id: 1, appointment_id: 2},
  {user_id: 1, appointment_id: 25},
  {user_id: 2, appointment_id: 25},
  {user_id: 3, appointment_id: 25},
  {user_id: 4, appointment_id: 25},
  {user_id: 5, appointment_id: 25},
  {user_id: 6, appointment_id: 25},
  {user_id: 7, appointment_id: 25},
  {user_id: 8, appointment_id: 25},
  {user_id: 9, appointment_id: 25},
  {user_id: 10, appointment_id: 25},
  {user_id: 11, appointment_id: 25},
  {user_id: 12, appointment_id: 25},
  {user_id: 13, appointment_id: 25},
  {user_id: 14, appointment_id: 25},
  {user_id: 15, appointment_id: 25},
  {user_id: 16, appointment_id: 25},
  {user_id: 17, appointment_id: 25},
  {user_id: 18, appointment_id: 25},
  {user_id: 19, appointment_id: 25},
  {user_id: 20, appointment_id: 25},
  {user_id: 21, appointment_id: 25},
  {user_id: 22, appointment_id: 25},
  {user_id: 23, appointment_id: 25},
  {user_id: 24, appointment_id: 25},
  {user_id: 1, appointment_id: 26},
  {user_id: 2, appointment_id: 26},
  {user_id: 3, appointment_id: 26},
  {user_id: 4, appointment_id: 26},
  {user_id: 18, appointment_id: 26},
  {user_id: 22, appointment_id: 26},
  {user_id: 23, appointment_id: 26},
  {user_id: 24, appointment_id: 26},
  {user_id: 1, appointment_id: 27},
  {user_id: 1, appointment_id: 28},
  {user_id: 2, appointment_id: 28},
  {user_id: 3, appointment_id: 28},
  {user_id: 4, appointment_id: 28},
  {user_id: 5, appointment_id: 28},
  {user_id: 6, appointment_id: 28},
  {user_id: 7, appointment_id: 28},
  {user_id: 8, appointment_id: 28},
  {user_id: 9, appointment_id: 28},
  {user_id: 10, appointment_id: 28},
  {user_id: 11, appointment_id: 28},
  {user_id: 12, appointment_id: 28},
  {user_id: 13, appointment_id: 28},
  {user_id: 14, appointment_id: 28},
  {user_id: 15, appointment_id: 28},
  {user_id: 16, appointment_id: 28},
  {user_id: 17, appointment_id: 28},
  {user_id: 18, appointment_id: 28},
  {user_id: 19, appointment_id: 28},
  {user_id: 20, appointment_id: 28},
  {user_id: 21, appointment_id: 28},
  {user_id: 22, appointment_id: 28},
  {user_id: 23, appointment_id: 28},
  {user_id: 24, appointment_id: 28},
  {user_id: 1, appointment_id: 29},
  {user_id: 2, appointment_id: 29},
  {user_id: 3, appointment_id: 29},
  {user_id: 4, appointment_id: 29},
  {user_id: 1, appointment_id: 30},
  {user_id: 2, appointment_id: 30},
  {user_id: 3, appointment_id: 30},
  {user_id: 4, appointment_id: 30},
  {user_id: 5, appointment_id: 30},
  {user_id: 6, appointment_id: 30},
  {user_id: 7, appointment_id: 30},
  {user_id: 8, appointment_id: 30},
  {user_id: 9, appointment_id: 30},
  {user_id: 10, appointment_id: 30},
  {user_id: 11, appointment_id: 30},
  {user_id: 12, appointment_id: 30},
  {user_id: 13, appointment_id: 30},
  {user_id: 14, appointment_id: 30},
  {user_id: 15, appointment_id: 30},
  {user_id: 16, appointment_id: 30},
  {user_id: 17, appointment_id: 30},
  {user_id: 18, appointment_id: 30},
  {user_id: 19, appointment_id: 30},
  {user_id: 20, appointment_id: 30},
  {user_id: 21, appointment_id: 30},
  {user_id: 22, appointment_id: 30},
  {user_id: 23, appointment_id: 30},
  {user_id: 24, appointment_id: 30},
  {user_id: 25, appointment_id: 30}
])
UserGroup.create!([
  {user_id: 1, group_id: 1, admin: nil},
  {user_id: 1, group_id: 2, admin: nil},
  {user_id: 18, group_id: 1, admin: nil},
  {user_id: 17, group_id: 1, admin: nil},
  {user_id: 15, group_id: 2, admin: nil},
  {user_id: 21, group_id: 1, admin: nil},
  {user_id: 16, group_id: 2, admin: nil},
  {user_id: 5, group_id: 2, admin: nil},
  {user_id: 9, group_id: 2, admin: nil},
  {user_id: 6, group_id: 2, admin: nil},
  {user_id: 9, group_id: 1, admin: nil},
  {user_id: 10, group_id: 2, admin: nil},
  {user_id: 7, group_id: 1, admin: nil},
  {user_id: 16, group_id: 1, admin: nil},
  {user_id: 12, group_id: 1, admin: nil},
  {user_id: 20, group_id: 1, admin: nil},
  {user_id: 5, group_id: 1, admin: nil},
  {user_id: 10, group_id: 1, admin: nil},
  {user_id: 12, group_id: 2, admin: nil},
  {user_id: 18, group_id: 2, admin: nil},
  {user_id: 11, group_id: 2, admin: nil},
  {user_id: 3, group_id: 2, admin: nil},
  {user_id: 14, group_id: 2, admin: nil},
  {user_id: 1, group_id: 17, admin: true},
  {user_id: 24, group_id: 2, admin: nil},
  {user_id: 18, group_id: 8, admin: nil},
  {user_id: 24, group_id: 1, admin: nil},
  {user_id: 1, group_id: 18, admin: true},
  {user_id: 22, group_id: 19, admin: true},
  {user_id: 22, group_id: 2, admin: true},
  {user_id: 22, group_id: 3, admin: nil},
  {user_id: 22, group_id: 1, admin: nil}
])
